### ISSUE TITLE
Discussion before DMCA

### ISSUE THREAD

**Issue by galnir** [ThaddeusKKR/Treble#1]
It would be great if you'd include a line in your README that states where the code for the main features came from, instead of claiming this code as your work. It's ironic that you wrote in the README that people need to give you credit if they use this code, which you yourself didn't.

I suggest you read the [GPL-3.0 license](https://github.com/galnir/Master-Bot/blob/master/LICENSE) and what a [DCMA](https://docs.github.com/en/github/site-policy/dmca-takedown-policy) is

**Comment by ThaddeusKKR** [comment]
Done
